import * as k8s from "@kubernetes/client-node";
import { app, BrowserWindow, ipcMain } from "electron";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// Handle IPC for getting contexts
ipcMain.handle("get-contexts", async () => {
  const kc = new k8s.KubeConfig();
  kc.loadFromDefault();
  const contexts = kc.getContexts().map((ctx) => ({
    name: ctx.name,
    cluster: ctx.cluster,
    user: ctx.user,
  }));
  return { contexts, currentContext: kc.currentContext };
});

// Handle IPC for switching context
ipcMain.handle("switch-context", async (event, contextName) => {
  const kc = new k8s.KubeConfig();
  kc.loadFromDefault();
  kc.setCurrentContext(contextName);
  return { success: true, currentContext: kc.currentContext };
});

// Handle IPC for getting pods
ipcMain.handle("get-pods", async (event, contextName) => {
  try {
    const kc = new k8s.KubeConfig();
    kc.loadFromDefault();

    // Switch to the specified context if provided
    if (contextName) {
      kc.setCurrentContext(contextName);
    }

    const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
    const podListResponse = await k8sApi.listPodForAllNamespaces();

    const pods =
      podListResponse?.items?.map((pod) => ({
        name: pod.metadata?.name || "",
        namespace: pod.metadata?.namespace || "",
        status: pod.status?.phase || "Unknown",
        ready:
          pod.status?.containerStatuses?.every(
            (cs: k8s.V1ContainerStatus) => cs.ready
          ) || false,
        restarts:
          pod.status?.containerStatuses?.reduce(
            (sum: number, cs: k8s.V1ContainerStatus) =>
              sum + (cs.restartCount || 0),
            0
          ) || 0,
        age: pod.metadata?.creationTimestamp
          ? Math.floor(
              (Date.now() -
                new Date(pod.metadata.creationTimestamp).getTime()) /
                (1000 * 60 * 60 * 24)
            )
          : 0,
        node: pod.spec?.nodeName || "Unknown",
      })) || [];

    return { success: true, pods };
  } catch (error) {
    console.error("Error getting pods:", error);
    return { success: false, error: error.message, pods: [] };
  }
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
